/*
 * ActivityInfo
 * Copyright (C) 2009-2013 UNICEF
 * Copyright (C) 2014-2018 BeDataDriven Groep B.V.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.activityinfo.store.spi;

import org.activityinfo.model.resource.ResourceId;

/**
 * Globally unique Id for a given blob content.
 * Blob Ids are generated by the client.
 */
public class BlobId {

    private String value;

    public BlobId(String value) {
        this.value = value;
    }

    public static BlobId generate() {
        return new BlobId(ResourceId.generateId().asString());
    }

    public String asString() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        BlobId blobId = (BlobId) o;

        if (value == null) {
            return blobId.value == null;
        } else {
            return value.equals(blobId.value);
        }
    }

    @Override
    public int hashCode() {
        return value != null ? value.hashCode() : 0;
    }
}
