package org.activityinfo.model.type;

import com.google.gson.JsonElement;
import com.google.gson.JsonPrimitive;

/**
 * A sequential file number, generated by the server when first saved.
 */
public class FileNumber implements FieldValue {

    private String string;

    public FileNumber(String string) {
        this.string = string;
    }

    @Override
    public FieldTypeClass getTypeClass() {
        return FileNumberType.TYPE_CLASS;
    }

    @Override
    public JsonElement toJsonElement() {
        return new JsonPrimitive(string);
    }
}
