package org.activityinfo.model.type;

import com.google.common.base.Strings;
import com.google.gson.JsonElement;
import com.google.gson.JsonPrimitive;

/**
 * A sequential file number, generated by the server when first saved.
 */
public class SerialNumber implements FieldValue {

    private int number;

    public SerialNumber(int serialNumber) {
        number = serialNumber;
    }

    @Override
    public FieldTypeClass getTypeClass() {
        return SerialNumberType.TYPE_CLASS;
    }

    @Override
    public JsonElement toJsonElement() {
        return new JsonPrimitive(number);
    }

    public int getNumber() {
        return number;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SerialNumber that = (SerialNumber) o;

        return number == that.number;
    }

    public String format() {
        return Strings.padStart(Integer.toString(number), 5, '0');
    }

    @Override
    public int hashCode() {
        return number;
    }

    @Override
    public String toString() {
        return "SerialNumber{" +
                "number=" + number +
                '}';
    }
}
