package org.activityinfo.model.type;

import com.google.common.base.Strings;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;

/**
 * A sequential file number, generated by the server when first saved.
 */
public class SerialNumber implements FieldValue {

    private final String prefix;
    private int number;

    public SerialNumber(int serialNumber) {
        number = serialNumber;
        prefix = null;
    }

    public SerialNumber(String prefix, int number) {
        this.prefix = prefix;
        this.number = number;
    }

    @Override
    public FieldTypeClass getTypeClass() {
        return SerialNumberType.TYPE_CLASS;
    }

    @Override
    public JsonElement toJsonElement() {
        if(prefix == null) {
            return new JsonPrimitive(number);
        } else {
            JsonObject object = new JsonObject();
            object.addProperty("prefix", prefix);
            object.addProperty("number", number);
            return object;
        }
    }

    public String getPrefix() {
        return prefix;
    }

    public int getNumber() {
        return number;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SerialNumber that = (SerialNumber) o;

        if (number != that.number) return false;
        return prefix != null ? prefix.equals(that.prefix) : that.prefix == null;

    }

    @Override
    public int hashCode() {
        int result = prefix != null ? prefix.hashCode() : 0;
        result = 31 * result + number;
        return result;
    }

    @Override
    public String toString() {
        return "SerialNumber{" +
                "prefix='" + prefix + '\'' +
                ", number=" + number +
                '}';
    }

    public boolean hasPrefix() {
        return !Strings.isNullOrEmpty(prefix);
    }
}
