/*
 * ActivityInfo
 * Copyright (C) 2009-2013 UNICEF
 * Copyright (C) 2014-2018 BeDataDriven Groep B.V.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.activityinfo.model.type;

import com.google.common.base.Strings;
import org.activityinfo.json.Json;
import org.activityinfo.json.JsonValue;

import static org.activityinfo.json.Json.createObject;

/**
 * A sequential file number, generated by the server when first saved.
 */
public class SerialNumber implements FieldValue {

    private final String prefix;
    private int number;

    public SerialNumber(int serialNumber) {
        number = serialNumber;
        prefix = null;
    }

    public SerialNumber(String prefix, int number) {
        this.prefix = prefix;
        this.number = number;
    }

    @Override
    public FieldTypeClass getTypeClass() {
        return SerialNumberType.TYPE_CLASS;
    }

    @Override
    public JsonValue toJson() {
        if(prefix == null) {
            return Json.create(number);
        } else {
            JsonValue object = createObject();
            object.put("prefix", prefix);
            object.put("number", number);
            return object;
        }
    }

    public String getPrefix() {
        return prefix;
    }

    public int getNumber() {
        return number;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SerialNumber that = (SerialNumber) o;

        if (number != that.number) return false;
        return prefix != null ? prefix.equals(that.prefix) : that.prefix == null;

    }

    @Override
    public int hashCode() {
        int result = prefix != null ? prefix.hashCode() : 0;
        result = 31 * result + number;
        return result;
    }

    @Override
    public String toString() {
        return "SerialNumber{" +
                "prefix='" + prefix + '\'' +
                ", number=" + number +
                '}';
    }

    public boolean hasPrefix() {
        return !Strings.isNullOrEmpty(prefix);
    }
}
